apiVersion: v1
kind: ReplicationController
metadata:
  name: mynginx-rc
spec:
replicas: 3
selector:
app: mylogin
templates:
  metadata:
     Labeles:
       app:mynginx
  spec:
  containers:
  - name: mynginx-container
    image: nginx
    ports:
      - containerPort: 80
