apiVersion: apps/v1
kind: service
metadata:
   name: mynginx-svc
   lables:
       app: mynginx
spec:
  type: NodePort
  ports:
   - port: 80
     nodePort: 30001
     protocol: TCP
  selector:
      app: mynginx

  